// <auto-generated />
using System;
using FoxData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoxData.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FoxDataDbContext))]
    partial class FoxDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.CollectionJobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<long>("LeaseGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("lease_generation");

                    b.Property<Guid?>("LeaseOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_owner_id");

                    b.Property<short>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_jobs_endpoint_idempotency");

                    b.HasIndex("EndpointId", "ScheduledFor")
                        .HasDatabaseName("ix_collection_jobs_endpoint_scheduled");

                    b.HasIndex("LeaseExpiresAt", "Id")
                        .HasDatabaseName("ix_collection_jobs_expired_lease")
                        .HasFilter("state IN ('leased','processing')");

                    b.HasIndex("AvailableAt", "Priority", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_collection_jobs_pending")
                        .HasFilter("state = 'pending'");

                    b.ToTable("collection_jobs", "ingest", t =>
                        {
                            t.HasCheckConstraint("ck_collection_jobs_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_collection_jobs_lease_generation", "lease_generation >= 0");

                            t.HasCheckConstraint("ck_collection_jobs_state", "state IN ('pending','leased','processing','completed','failed','cancelled')");
                        });
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.EndpointPollStateRow", b =>
                {
                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset?>("LastHttpResponseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_http_response_at");

                    b.Property<Guid?>("LastProcessedFetchId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_processed_fetch_id");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<Guid?>("LatestValidationFetchId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_validation_fetch_id");

                    b.Property<DateTimeOffset?>("NextTargetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_target_at");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("policy_version");

                    b.Property<Guid?>("RepresentationFetchId")
                        .HasColumnType("uuid")
                        .HasColumnName("representation_fetch_id");

                    b.Property<DateTimeOffset?>("RetryEligibleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retry_eligible_at");

                    b.Property<DateTimeOffset?>("SourceCacheEligibleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_cache_eligible_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<string>("ValidatorEtag")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("validator_etag");

                    b.HasKey("EndpointId");

                    b.HasIndex("LastProcessedFetchId");

                    b.HasIndex("LatestValidationFetchId");

                    b.HasIndex("RepresentationFetchId");

                    b.ToTable("endpoint_poll_state", "ingest", t =>
                        {
                            t.HasCheckConstraint("ck_endpoint_poll_state_consecutive_failures", "consecutive_failures >= 0");
                        });
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.EndpointRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapabilityKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("capability_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("SemanticKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("semantic_key");

                    b.Property<Guid>("ShardId")
                        .HasColumnType("uuid")
                        .HasColumnName("shard_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("ShardId", "SemanticKey")
                        .IsUnique()
                        .HasDatabaseName("ux_endpoints_shard_semantic_key");

                    b.ToTable("endpoints", "sources");
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.EndpointStateRow", b =>
                {
                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<Guid?>("ActiveAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_attempt_id");

                    b.Property<long>("FenceToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("fence_token");

                    b.Property<Guid?>("LastCurrentCaptureAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_current_capture_attempt_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.HasKey("EndpointId");

                    b.HasIndex("ActiveAttemptId");

                    b.HasIndex("LastCurrentCaptureAttemptId");

                    b.ToTable("endpoint_state", "ingest", t =>
                        {
                            t.HasCheckConstraint("ck_endpoint_state_fence_token", "fence_token >= 0");
                        });
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.FetchRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<string>("BodyErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("body_error_code");

                    b.Property<string>("CacheControl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cache_control");

                    b.Property<string>("ContentEncoding")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_encoding");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<long?>("DeclaredLength")
                        .HasColumnType("bigint")
                        .HasColumnName("declared_length");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("MediaType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("media_type");

                    b.Property<Guid?>("PayloadId")
                        .HasColumnType("uuid")
                        .HasColumnName("payload_id");

                    b.Property<Guid?>("PriorFetchId")
                        .HasColumnType("uuid")
                        .HasColumnName("prior_fetch_id");

                    b.Property<DateTimeOffset>("RequestStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_started_at");

                    b.Property<DateTimeOffset?>("ResponseStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_started_at");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("RetryAfter")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("retry_after");

                    b.Property<long?>("SourceAgeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("source_age_seconds");

                    b.Property<DateTimeOffset?>("SourceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_date");

                    b.Property<string>("SourceEtag")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_etag");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TransportKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transport_kind");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_fetches_attempt");

                    b.HasIndex("PayloadId")
                        .HasDatabaseName("ix_fetches_payload");

                    b.HasIndex("PriorFetchId")
                        .HasDatabaseName("ix_fetches_prior_fetch");

                    b.HasIndex("EndpointId", "RetrievedAt", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_fetches_endpoint_retrieved");

                    b.ToTable("fetches", "evidence", t =>
                        {
                            t.HasCheckConstraint("ck_fetches_declared_length", "declared_length IS NULL OR declared_length >= 0");

                            t.HasCheckConstraint("ck_fetches_duration_ms", "duration_ms >= 0");

                            t.HasCheckConstraint("ck_fetches_source_age_seconds", "source_age_seconds IS NULL OR source_age_seconds >= 0");
                        });
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.IngestionAttemptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<string>("ErrorClass")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("error_class");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("ExchangeAuthorizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exchange_authorized_at");

                    b.Property<long?>("FenceToken")
                        .HasColumnType("bigint")
                        .HasColumnName("fence_token");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<long>("LeaseGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("lease_generation");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("outcome_code");

                    b.Property<DateTimeOffset?>("RawDurableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raw_durable_at");

                    b.Property<DateTimeOffset?>("RecoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovered_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_attempts_job_number");

                    b.HasIndex("State", "StartedAt")
                        .HasDatabaseName("ix_attempts_state_started");

                    b.ToTable("attempts", "ingest", t =>
                        {
                            t.HasCheckConstraint("ck_attempts_attempt_number", "attempt_number > 0");

                            t.HasCheckConstraint("ck_attempts_fence_token", "fence_token IS NULL OR fence_token >= 0");

                            t.HasCheckConstraint("ck_attempts_lease_generation", "lease_generation > 0");

                            t.HasCheckConstraint("ck_attempts_state", "state IN ('created','fenced','exchange_authorized','raw_durable','completed','failed','uncertain','superseded','captured_late')");
                        });
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.PayloadRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ux_payloads_sha256");

                    b.ToTable("payloads", "evidence", t =>
                        {
                            t.HasCheckConstraint("ck_payloads_body_length", "octet_length(body) = byte_length");

                            t.HasCheckConstraint("ck_payloads_byte_length", "byte_length >= 0");

                            t.HasCheckConstraint("ck_payloads_sha256_length", "octet_length(sha256) = 32");
                        });
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.ShardRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_shards_source_key");

                    b.ToTable("shards", "sources");
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.SourceParseRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdapterVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("adapter_version");

                    b.Property<string>("CapabilityKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("capability_key");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("FingerprintAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_algorithm");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("outcome");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("parser_version");

                    b.Property<Guid>("RepresentationFetchId")
                        .HasColumnType("uuid")
                        .HasColumnName("representation_fetch_id");

                    b.Property<long?>("SourceLastUpdated")
                        .HasColumnType("bigint")
                        .HasColumnName("source_last_updated");

                    b.Property<long?>("SourceVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_version");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StructuralFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("structural_fingerprint");

                    b.Property<int>("UnknownCodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("unknown_code_count");

                    b.Property<int>("UnknownPropertyCount")
                        .HasColumnType("integer")
                        .HasColumnName("unknown_property_count");

                    b.HasKey("Id");

                    b.HasIndex("Outcome", "CreatedAt")
                        .HasDatabaseName("ix_source_parse_runs_outcome_created");

                    b.HasIndex("RepresentationFetchId", "CapabilityKey", "ParserVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_source_parse_runs_representation_capability_parser");

                    b.ToTable("source_parse_runs", "evidence", t =>
                        {
                            t.HasCheckConstraint("ck_source_parse_runs_completed_after_started", "completed_at >= started_at");

                            t.HasCheckConstraint("ck_source_parse_runs_unknown_code_count", "unknown_code_count >= 0");

                            t.HasCheckConstraint("ck_source_parse_runs_unknown_property_count", "unknown_property_count >= 0");
                        });
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.SourceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("transaction_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_sources_key");

                    b.ToTable("sources", "sources");
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.CollectionJobRow", b =>
                {
                    b.HasOne("FoxData.Infrastructure.Persistence.EndpointRow", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.EndpointPollStateRow", b =>
                {
                    b.HasOne("FoxData.Infrastructure.Persistence.EndpointRow", null)
                        .WithOne()
                        .HasForeignKey("FoxData.Infrastructure.Persistence.EndpointPollStateRow", "EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoxData.Infrastructure.Persistence.FetchRow", null)
                        .WithMany()
                        .HasForeignKey("LastProcessedFetchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoxData.Infrastructure.Persistence.FetchRow", null)
                        .WithMany()
                        .HasForeignKey("LatestValidationFetchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoxData.Infrastructure.Persistence.FetchRow", null)
                        .WithMany()
                        .HasForeignKey("RepresentationFetchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.EndpointRow", b =>
                {
                    b.HasOne("FoxData.Infrastructure.Persistence.ShardRow", null)
                        .WithMany()
                        .HasForeignKey("ShardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.EndpointStateRow", b =>
                {
                    b.HasOne("FoxData.Infrastructure.Persistence.IngestionAttemptRow", null)
                        .WithMany()
                        .HasForeignKey("ActiveAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoxData.Infrastructure.Persistence.EndpointRow", null)
                        .WithOne()
                        .HasForeignKey("FoxData.Infrastructure.Persistence.EndpointStateRow", "EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoxData.Infrastructure.Persistence.IngestionAttemptRow", null)
                        .WithMany()
                        .HasForeignKey("LastCurrentCaptureAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.FetchRow", b =>
                {
                    b.HasOne("FoxData.Infrastructure.Persistence.IngestionAttemptRow", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoxData.Infrastructure.Persistence.EndpointRow", null)
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoxData.Infrastructure.Persistence.PayloadRow", null)
                        .WithMany()
                        .HasForeignKey("PayloadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoxData.Infrastructure.Persistence.FetchRow", null)
                        .WithMany()
                        .HasForeignKey("PriorFetchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.IngestionAttemptRow", b =>
                {
                    b.HasOne("FoxData.Infrastructure.Persistence.CollectionJobRow", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.ShardRow", b =>
                {
                    b.HasOne("FoxData.Infrastructure.Persistence.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FoxData.Infrastructure.Persistence.SourceParseRunRow", b =>
                {
                    b.HasOne("FoxData.Infrastructure.Persistence.FetchRow", null)
                        .WithMany()
                        .HasForeignKey("RepresentationFetchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
