<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../FoxData.Sources.Abstractions/FoxData.Sources.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../.work/contracts/internal/source/warapi-map-taxonomy@1.json"
                      LogicalName="FoxData.Sources.WarApi.Contracts.warapi-map-taxonomy@1.json" />
    <EmbeddedResource Include="../../.work/contracts/internal/source/warapi-map-quality-policy@1.json"
                      LogicalName="FoxData.Sources.WarApi.Contracts.warapi-map-quality-policy@1.json" />
    <EmbeddedResource Include="../../.work/contracts/internal/source/warapi-map-quality-policy@2.json"
                      LogicalName="FoxData.Sources.WarApi.Contracts.warapi-map-quality-policy@2.json" />
  </ItemGroup>
</Project>
